### PR TITLE
Append proxies instead of replacing

### LINKED ISSUE #16: Existing custom proxies are overwritten by this Gem
We had an issue come up where we had specified a trusted proxy in our application.rb but it wasn't taking effect. We traced the issue to this gem overwriting any other existing trusted proxies.

What's the recommended way to use this gem with other trusted proxies? Would you be open to PR that merges instead of replaces?

Something like this:

```ruby
        if app.config.action_pack_cloudfront.load_proxies
          trusted_proxies = ActionPack::Cloudfront::IpRanges.trusted_proxies
          existing_proxies = Array(app.config.action_dispatch.trusted_proxies)

          app.config.action_dispatch.trusted_proxies = trusted_proxies.concat(existing_proxies).uniq
        end
```

### PR DESCRIPTION
**Pull request by jhubert**
This change appends any existing proxies to the cloudfront proxies that are being added.

It also runs uniq so that we have a clean list.

Closes #16

### CODE REVIEW

**Comment by jhubert** [comment]
We're running this in production with no issues.

**Comment by metaskills** [comment]
Just pushed v1.2.0 to rubygems. https://rubygems.org/gems/actionpack-cloudfront

**Comment by metaskills** [comment]
Also, thanks!!!

**Comment by jhubert** [comment]
Thanks for the super-fast response time. 🙌

**Pull request merged**
